### ISSUE TITLE
Installer requires admin access. Should support local install.

### ISSUE THREAD

**Issue by iplayfast** [nomic-ai/gpt4all-chat#13]
So frustrated trying to use it. 
1. it insists on installing as root. I say NO! and give it a local directory to install into. 
2. It downloads the file for 5 minutes, then uncompresses them for a few minutes, and then tries to add an icon to the desktop (without permission). It can do this, so up pops an abort message with some buttons, the default is abort. If you happen to be typing when this message comes up, it aborts before you can even read the message. 
3. It offers a command to use to run the software (perfect!), so I use that. and it then deletes the installation directory.

Try to install from github,
1. insists on qt6 install (why? WTF does chat software have to do with qt?) So have to install that. 
2. Can't find quick and won't compile
3. link provided for download, doesn't actually go to downloadable files. (never didi find them).

**Comment by anthonywww** [comment]
Yeah I don't think the installer should require root access. Also there should be a CLI option.

**Comment by atrblizzard** [comment]
Also for me for some reason it kept starting SteamVR. It makes zero sense.

**Comment by manyoso** [comment]
Sorry for the issues. Will work on getting a local install with non admin access. In meantime have to install it as admin.

**Comment by anthonywww** [comment]
In the meantime I've been comparing https://github.com/nomic-ai/gpt4all (LLaMa) to the gpt4-j model. Does this version have a CLI interface or a way to query prompts via an external program? -- Also not sure if this is out of scope, but I noticed at least with the LLaMa model when I asked it to execute commands on the local system it was referencing "/home/ubuntu" instead of my actual filesystem. I assume that's because that's how it was trained and it has no perception of the actual filesystem it's running on?

**Comment by letapk** [comment]
I ran the installer in a local directory, as a user without "sudo" or root.
During installation, the installer attempts to write a couple of times to the /usr directory, and fails, since this requires root access. On both occasions a pop-up window appears, and clicking "Ignore" seems to be okay because the installation proceeds to completion.
Clicking "chat" brings up the UI. While it is slow on my machine, probably because of modest hardware, the program seems to be functional.
Linux, Kubuntu 22.04, Intel core i5, 8Gb RAM.

**Comment by manyoso** [comment]
Done
