### ISSUE TITLE
The problem with using the Russian language AI.

### ISSUE THREAD

**Issue by Arturio48** [nomic-ai/gpt4all-chat#20]
The AI tries to answer in Russian, using Cyrillic and Latin characters. There is no logic in the words, and they are not recognized by native speakers. 
![photo_2023-04-14_14-44-04](https://user-images.githubusercontent.com/108017166/232043664-b668c769-dbe9-4046-b2f7-3c98e42b1747.jpg)

**Comment by gmy77** [comment]
QT fonts?

**Comment by gmy77** [comment]
> > QT-шрифты?
> 
> Didn't do any font manipulation. Everything is default for windows 10.

No i think about during the QT DEV...

**Comment by inxisx** [comment]
no way for me
![privet](https://user-images.githubusercontent.com/129610652/232062800-c977471a-1a74-495c-ac92-c927bee2407d.JPG)

**Comment by inxisx** [comment]
French also

**Comment by EvgTG** [comment]
Same thing on Mac.

**Comment by AndriyMulyar** [comment]
The base model is not currently multilingual so unfortunately fails to be useful in language others than english. this is quickly improving.

**Comment by inxisx** [comment]
![chat4](https://user-images.githubusercontent.com/129610652/233637942-35fde545-1d85-4f56-8e75-f218143931f0.JPG)

**Comment by inxisx** [comment]
For some, your campaign's chance to join now for some time will be so much better. Is your other bana campaign looking like crap? So, what are you going to attack from here with your battles and provocateurs right now? You are good, your campaign is not all about you and not in your other family, even if it would work for you otherwise. In a bad campaign, your bana is opened and right now you are seen as a real diasterosa and dotsep in some parts of the world. At the moment I am helpless, and in the future you will even have a strong vision of the blackmailed, which our campaign has for the world and universality, and our poganishka. For whom your campaign will not be open to everyone, but in the morning you may listen to the maboudier who has you

**Comment by inxisx** [comment]
still typing...I will wait for the end of his message.

**Comment by manyoso** [comment]
Multiple languages are in the works.
